import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-projects-en',
  templateUrl: './projects-en.component.html',
  styleUrls: ['./projects-en.component.scss']
})
export class ProjectsEnComponent implements OnInit {

  constructor() { }

  projects = [
    { titulo: 'Rastreei: Tracking', detalhes: 'Rastreei is a vehicle tracking and management system aimed at benefit associations, developed with a focus on efficiency and technology. In the development, I created custom codes that automate essential tracking processes, optimizing management and reducing operational costs. Additionally, I implemented new features that expand the system’s functionalities, bringing greater accuracy and security for associates. The Rastreei system combines advanced technology with strategic automation, being an example of how innovation can transform tracking and management services in today’s market.', imagem: '../../../../../../../assets/img/apps/rastreei.png', url: 'https://rastreei.com/' },
    { titulo: 'Spektrum Glasses', detalhes: 'Spektrum Glasses is an online store specializing in the sale of sunglasses and prescription glasses. The project was developed with a focus on user experience, offering an intuitive and responsive interface. We implemented a real-time inventory management system, allowing customers to view product availability. Additionally, the platform features a secure payment system and various shipping options, ensuring a smooth and reliable shopping experience.', imagem: '../../../../../../../assets/img/clients/glasses.png', url: 'https://spektrumglasses.com/' },
    { titulo: 'Arthificial', detalhes: 'Arthificial is a platform that offers hosting services and development of customized digital solutions. The project was created to meet the specific needs of companies looking for a robust and scalable online presence. We implemented a secure and reliable hosting infrastructure, as well as web development services that include responsive design, system integration, and search engine optimization. The platform also offers ongoing technical support and consulting to ensure that clients maximize the potential of their digital solutions.', imagem: '../../../../../../../assets/img/clients/arthificial-removebg-preview.png', url: 'https://arthificial.com/' },
    { titulo: 'Facilite: Title Broker', detalhes: 'Facilite is a title and credit brokerage that offers personalized financial solutions for investors. The system was developed to facilitate the buying and selling of titles, with a user-friendly interface that allows users to track their operations in real-time. We implemented market analysis tools and detailed reports, helping investors make informed decisions. The security of transactions and integration with banks and financial institutions are priorities of the system.', imagem: '../../../../../../../assets/img/clients/facilite-removebg-preview.png', url: 'https://facilite-brasil.com.br/' },
    { titulo: 'Fradema: Consultants', detalhes: 'Fradema is a tax consultancy that offers specialized services for companies looking to optimize their tax burden and ensure compliance with legislation. The developed system allows for detailed analysis of tax data, identification of savings opportunities, and generation of customized reports. The platform also includes document management tools and communication with clients, facilitating the monitoring of processes and transparency in operations.', imagem: '../../../../../../../assets/img/clients/fradema-removebg-preview.png', url: 'https://www.fradema.com.br/' },
    { titulo: 'Grupo2E: Management', detalhes: 'Grupo2E is an asset management platform designed to optimize consumer relationships and the internal organization of the company. During development, I implemented customized functionalities that allow efficient management of customer data, with tools for metric analysis and detailed report generation. Integration with other corporate systems was a priority, ensuring a unified experience for users. The result is a robust solution that improves engagement, increases productivity, and facilitates decision-making processes.', imagem: '../../../../../../../assets/img/clients/g2e-removebg-preview.png', url: 'https://sistema.grupo2e.com.br/' },
    { titulo: 'Indike.me: Indicators', detalhes: 'Indike.me is an indicator platform developed to provide valuable insights through data analysis. During development, I implemented advanced algorithms that allow for the collection, processing, and visualization of data in real-time. The platform offers an intuitive interface for users, facilitating the interpretation of indicators and assisting in strategic decision-making. Integration with various data sources ensures a comprehensive and accurate view, making Indike.me an essential tool for companies looking to optimize their operations and strategies.', imagem: '../../../../../../../assets/img/clients/indike-removebg-preview.png', url: '' },
    { titulo: 'Gestix: Management System', detalhes: 'Gestix is a business management system developed to optimize internal processes and improve operational efficiency. During development, I implemented customized modules for financial control, inventory management, and automation of administrative tasks. The platform also offers data analysis tools and report generation, allowing a comprehensive and detailed view of the company’s operations. Integration with external systems ensures a unified experience and facilitates strategic decision-making.', imagem: '../../../../../../../assets/img/clients/gestix-sistema-removebg-preview.png', url: '' },
    { titulo: 'APP Technician: Service Order Control', detalhes: 'The APP Technician Installer is an application developed to manage and control service orders for installation technicians. During development, I implemented functionalities that allow the creation, assignment, and tracking of service orders in real-time. The platform offers an intuitive interface for technicians, facilitating the update of order statuses and communication with the support team. Integration with management systems ensures a complete view of operations, improving efficiency and the quality of the service provided.', imagem: '../../../../../../../assets/img/clients/app-removebg-preview.png', url: '' },
    { titulo: 'QRBand: Tracking', detalhes: 'QRBand is an innovative tracking solution that uses QR code technology to monitor assets and facilitate logistics. The system allows users to scan QR codes to access real-time information about the location and status of tracked items. During development, I implemented functionalities that ensure data security and integration with inventory management systems, providing an efficient and practical experience for users.', imagem: '../../../../../../../assets/img/clients/qr-removebg-preview.png', url: 'https://www.qrband.com.br/' },
    { titulo: 'R2: Fleet Management', detalhes: 'R2 is a fleet management platform aimed at optimizing the control and operation of vehicles in companies. The system allows real-time monitoring of vehicle locations, maintenance management, and performance analysis. During development, I implemented functionalities that ensure data security and integration with GPS systems, providing a comprehensive and detailed view of the fleet, improving operational efficiency and reducing costs.', imagem: '../../../../../../../assets/img/clients/r2-removebg-preview.png', url: 'https://r2.softbite.com.br/' },
    { titulo: 'FaleFlex: Telephony', detalhes: 'FaleFlex is a telephony platform that offers integrated communication solutions for companies. The system allows call management, conversation recording, and performance metric analysis. During development, I implemented functionalities that ensure the security of communications and integration with CRM systems, providing a unified and efficient experience for users.', imagem: '../../../../../../../assets/img/clients/faleflex-removebg-preview.png', url: '' },
    { titulo: 'StartzPro: E-book Store', detalhes: 'StartzPro is an e-commerce platform dedicated to selling e-books. The project was developed to provide a simple and intuitive shopping experience, with a responsive design that adapts to different devices. We implemented an advanced search system that allows users to quickly find the desired titles, as well as a personalized recommendation system based on purchase history. The platform also features secure payment options and a user account management system, facilitating access and purchase of digital content.', imagem: '../../../../../../../assets/img/clients/sp-removebg-preview.png', url: '' },
    { titulo: 'Codando: Study Platform', detalhes: 'Codando is an online study platform that offers courses and educational materials for developers and programming enthusiasts. The project was developed to provide an interactive learning experience, with videos, quizzes, and discussion forums. We implemented a progress tracking system that allows users to monitor their performance and complete courses efficiently. The platform also features an active community where users can share knowledge and experiences.', imagem: '../../../../../../../assets/img/clients/codando-removebg-preview.png', url: '' },
    { titulo: 'AWS Cost Optimization', detalhes: 'This project was applied at the company Rastreei to help optimize its costs in the AWS cloud. Through a detailed analysis of resource usage, we implemented strategies that significantly reduced expenses without compromising performance. We used monitoring tools and reports to identify areas of waste and suggest improvements, resulting in more efficient resource management and substantial savings for clients.', imagem: '../../../../../../../assets/img/clients/aws-removebg-preview.png', url: '' },
  ]

  ngOnInit(): void {
  }

}